spring:
  profiles:
    active: dev
  application:
    name: md-agent
  datasource:
    url: "jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.db-name}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
    username: ${mysql.username}
    password: ${mysql.password}
  sql:
    init:
      mode: ${DB_INIT_MODE:always}
      schema-locations: "${DB_SCHEMA_LOCATION:optional:file:static/init.sql}"
  ai:
    openai:
      base-url: ${AI_QWEN_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode/v1}
      api-key: ${ai.qwen.api-key}
      chat:
        options:
          model: ${ai.qwen.model[0]}

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: ${SERVER_PORT:8080}
